# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1125, 791)
        Form.setMinimumSize(QtCore.QSize(1000, 600))
        Form.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.border = QtWidgets.QFrame(Form)
        self.border.setStyleSheet("QFrame#border{\n"
"    background-color: rgb(19, 22, 25);\n"
"    border-radius:10px;\n"
"border:2px solid rgb(0, 196, 255);\n"
"\n"
"}")
        self.border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border.setObjectName("border")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.border)
        self.verticalLayout.setContentsMargins(2, 0, 0, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background = QtWidgets.QFrame(self.border)
        self.background.setStyleSheet("QFrame#background{\n"
"    border-image: url(:/bg/bg/abstract-background-279.jpg);\n"
"border-radius:10px;\n"
"border:0px;\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.gridLayout = QtWidgets.QGridLayout(self.background)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.imageContainer = QtWidgets.QFrame(self.background)
        self.imageContainer.setStyleSheet("QFrame{\n"
"border-image:none;\n"
"background-color: rgba(19, 22, 25,0);\n"
"border-radius:0px;\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.imageContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageContainer.setObjectName("imageContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.imageContainer)
        self.horizontalLayout_5.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.optionBar = QtWidgets.QFrame(self.imageContainer)
        self.optionBar.setMinimumSize(QtCore.QSize(0, 0))
        self.optionBar.setMaximumSize(QtCore.QSize(0, 16777215))
        self.optionBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.optionBar.setBaseSize(QtCore.QSize(0, 0))
        self.optionBar.setStyleSheet("QFrame{\n"
"border:0px;\n"
"background-color: rgba(19, 22, 25,150);\n"
"\n"
"border-radius:0px;\n"
"}")
        self.optionBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.optionBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.optionBar.setObjectName("optionBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.optionBar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.optionBar)
        self.scrollArea.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 180, 630))
        self.scrollAreaWidgetContents.setStyleSheet("border:none;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hoeheLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hoeheLbl.setStyleSheet("color:white;")
        self.hoeheLbl.setObjectName("hoeheLbl")
        self.gridLayout_2.addWidget(self.hoeheLbl, 9, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 11, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.blurValLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.blurValLbl.setMinimumSize(QtCore.QSize(25, 0))
        self.blurValLbl.setMaximumSize(QtCore.QSize(25, 16777215))
        self.blurValLbl.setStyleSheet("color:white;")
        self.blurValLbl.setText("")
        self.blurValLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.blurValLbl.setObjectName("blurValLbl")
        self.gridLayout_2.addWidget(self.blurValLbl, 1, 3, 1, 1)
        self.brightValLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.brightValLbl.setMaximumSize(QtCore.QSize(25, 16777215))
        self.brightValLbl.setStyleSheet("color:white;")
        self.brightValLbl.setText("")
        self.brightValLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.brightValLbl.setObjectName("brightValLbl")
        self.gridLayout_2.addWidget(self.brightValLbl, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 6, 0, 1, 1)
        self.breiteLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.breiteLbl.setStyleSheet("color:white;")
        self.breiteLbl.setObjectName("breiteLbl")
        self.gridLayout_2.addWidget(self.breiteLbl, 8, 0, 1, 1)
        self.clrMapCombo = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.clrMapCombo.setStyleSheet("QComboBox{\n"
"color:white\n"
"}\n"
"\n"
"QListView{\n"
"color:white;\n"
"}")
        self.clrMapCombo.setMaxVisibleItems(20)
        self.clrMapCombo.setObjectName("clrMapCombo")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.clrMapCombo.addItem("")
        self.gridLayout_2.addWidget(self.clrMapCombo, 5, 1, 1, 2)
        self.brightSlide = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.brightSlide.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgba(0, 0, 0, 5);\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: rgba(0, 0, 0, 5);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.brightSlide.setMinimum(-500)
        self.brightSlide.setMaximum(255)
        self.brightSlide.setProperty("value", 0)
        self.brightSlide.setOrientation(QtCore.Qt.Horizontal)
        self.brightSlide.setObjectName("brightSlide")
        self.gridLayout_2.addWidget(self.brightSlide, 3, 1, 1, 2)
        self.brightnessLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.brightnessLbl.setStyleSheet("color:white;")
        self.brightnessLbl.setObjectName("brightnessLbl")
        self.gridLayout_2.addWidget(self.brightnessLbl, 3, 0, 1, 1)
        self.blurLbl_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.blurLbl_2.setStyleSheet("color:white;\n"
"font: 12pt \"Segoe UI\";\n"
"border-bottom:1px solid white;")
        self.blurLbl_2.setObjectName("blurLbl_2")
        self.gridLayout_2.addWidget(self.blurLbl_2, 0, 0, 1, 4)
        self.blurSlide = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.blurSlide.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgba(0, 0, 0, 5);\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: rgba(0, 0, 0, 5);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.blurSlide.setMaximum(100)
        self.blurSlide.setProperty("value", 0)
        self.blurSlide.setOrientation(QtCore.Qt.Horizontal)
        self.blurSlide.setObjectName("blurSlide")
        self.gridLayout_2.addWidget(self.blurSlide, 1, 1, 1, 2)
        self.breite = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.breite.setStyleSheet("color:white;\n"
"border:1px solid rgba(255, 255, 255, 55);")
        self.breite.setObjectName("breite")
        self.gridLayout_2.addWidget(self.breite, 8, 1, 1, 2)
        self.blurLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.blurLbl.setStyleSheet("color:white;")
        self.blurLbl.setObjectName("blurLbl")
        self.gridLayout_2.addWidget(self.blurLbl, 1, 0, 1, 1)
        self.hoehe = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.hoehe.setStyleSheet("color:white;\n"
"border:1px solid rgba(255, 255, 255, 55);")
        self.hoehe.setObjectName("hoehe")
        self.gridLayout_2.addWidget(self.hoehe, 9, 1, 1, 2)
        self.maaLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.maaLbl.setStyleSheet("color:white;\n"
"font: 12pt \"Segoe UI\";\n"
"border-bottom:1px solid white;")
        self.maaLbl.setObjectName("maaLbl")
        self.gridLayout_2.addWidget(self.maaLbl, 7, 0, 1, 4)
        self.widthHeightBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.widthHeightBtn.setMinimumSize(QtCore.QSize(50, 30))
        self.widthHeightBtn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widthHeightBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 196, 255, 150);\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 196, 255, 230);\n"
"}")
        self.widthHeightBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/4115236-delete-min-minus_114f026.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.widthHeightBtn.setIcon(icon)
        self.widthHeightBtn.setIconSize(QtCore.QSize(14, 14))
        self.widthHeightBtn.setObjectName("widthHeightBtn")
        self.gridLayout_2.addWidget(self.widthHeightBtn, 10, 0, 1, 3)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_5.addWidget(self.optionBar)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.imageContainer)
        self.scrollArea_2.setStyleSheet("\n"
"QScrollBar:horizontal\n"
"    {\n"
"        height: 15px;\n"
"        margin: 3px 15px 3px 15px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"        background-color: rgba(0, 0, 0,0);\n"
"    }\n"
"\n"
"    QScrollBar::handle:horizontal\n"
"    {\n"
"        background-color: rgba(0, 230, 255, 145);\n"
"        min-width: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:horizontal\n"
"    {\n"
"        margin: 0px 3px 0px 3px;\n"
"        border-image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
"        width: 10px;\n"
"        height: 10px;\n"
"        subcontrol-position: right;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:horizontal\n"
"    {\n"
"        margin: 0px 3px 0px 3px;\n"
"        border-image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: left;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:horizontal:hover,QScrollBar::add-line:horizontal:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/right_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: right;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"\n"
"    QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/left_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: left;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"\n"
"    QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar:vertical\n"
"    {\n"
"        background-color: rgba(0, 0, 0, 0);\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgba(0, 230, 255, 145);\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1091, 665))
        self.scrollAreaWidgetContents_2.setStyleSheet("background:rgba(0, 0, 0, 0)")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.imageLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.imageLbl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imageLbl.setStyleSheet("QLabel{\n"
"background:none;\n"
"border-image:none;\n"
"border:0px;\n"
"\n"
"}")
        self.imageLbl.setText("")
        self.imageLbl.setScaledContents(True)
        self.imageLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLbl.setObjectName("imageLbl")
        self.verticalLayout_5.addWidget(self.imageLbl, 0, QtCore.Qt.AlignHCenter)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_5.addWidget(self.scrollArea_2)
        self.gridLayout.addWidget(self.imageContainer, 2, 2, 1, 1)
        self.statusBar = QtWidgets.QFrame(self.background)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 30))
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.statusBar.setStyleSheet("QFrame{\n"
"border-image:none;\n"
"background-color: rgba(0, 234, 255, 100);\n"
"border-bottom-left-radius:6px;\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:6px;\n"
"border-right:2px solid black;\n"
"\n"
"}")
        self.statusBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusBar.setObjectName("statusBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.statusBar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pathLbl = QtWidgets.QLabel(self.statusBar)
        self.pathLbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 7pt \"Segoe UI\";\n"
"background:none;\n"
"border:0px;")
        self.pathLbl.setObjectName("pathLbl")
        self.horizontalLayout_4.addWidget(self.pathLbl)
        self.gridLayout.addWidget(self.statusBar, 3, 0, 1, 3)
        self.toolBar = QtWidgets.QFrame(self.background)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 30))
        self.toolBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.toolBar.setStyleSheet("QFrame{\n"
"border-image:none;\n"
"background-color: rgba(19, 22, 25,220);\n"
"border-bottom-left-radius:0px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-right-radius:10px;\n"
"}")
        self.toolBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBar.setObjectName("toolBar")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.toolBar)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.minBtn = QtWidgets.QPushButton(self.toolBar)
        self.minBtn.setMinimumSize(QtCore.QSize(50, 30))
        self.minBtn.setMaximumSize(QtCore.QSize(50, 30))
        self.minBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 196, 255, 150);\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 196, 255, 230);\n"
"}")
        self.minBtn.setText("")
        self.minBtn.setIcon(icon)
        self.minBtn.setIconSize(QtCore.QSize(14, 14))
        self.minBtn.setObjectName("minBtn")
        self.gridLayout_3.addWidget(self.minBtn, 0, 3, 1, 1)
        self.appName = QtWidgets.QLabel(self.toolBar)
        self.appName.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:none;")
        self.appName.setObjectName("appName")
        self.gridLayout_3.addWidget(self.appName, 0, 0, 1, 3)
        self.exitBtn = QtWidgets.QPushButton(self.toolBar)
        self.exitBtn.setMinimumSize(QtCore.QSize(50, 30))
        self.exitBtn.setMaximumSize(QtCore.QSize(50, 30))
        self.exitBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"border:0px;\n"
"border-top-right-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 196, 255, 150);\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 196, 255, 230);\n"
"}")
        self.exitBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/4115230-cancel-close-cross-deleste_114048.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon1)
        self.exitBtn.setObjectName("exitBtn")
        self.gridLayout_3.addWidget(self.exitBtn, 0, 5, 1, 1)
        self.maxBtn = QtWidgets.QPushButton(self.toolBar)
        self.maxBtn.setMinimumSize(QtCore.QSize(50, 30))
        self.maxBtn.setMaximumSize(QtCore.QSize(50, 30))
        self.maxBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 196, 255, 150);\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 196, 255, 230);\n"
"}")
        self.maxBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/window_maximGize_icon_181228.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxBtn.setIcon(icon2)
        self.maxBtn.setIconSize(QtCore.QSize(16, 16))
        self.maxBtn.setCheckable(True)
        self.maxBtn.setObjectName("maxBtn")
        self.gridLayout_3.addWidget(self.maxBtn, 0, 4, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.toolBar, 0, 0, 1, 3)
        self.navBar = QtWidgets.QFrame(self.background)
        self.navBar.setMinimumSize(QtCore.QSize(0, 40))
        self.navBar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.navBar.setStyleSheet("QFrame#navBar{\n"
"border-image:none;\n"
"background-color: rgba(19, 22, 25,150);\n"
"\n"
"border-radius:0px;\n"
"border-bottom:2px solid black;\n"
"}")
        self.navBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navBar.setObjectName("navBar")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.navBar)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.navBar)
        self.frame_2.setMinimumSize(QtCore.QSize(50, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(50, 40))
        self.frame_2.setStyleSheet("background:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.saveBtn = QtWidgets.QPushButton(self.frame_2)
        self.saveBtn.setMinimumSize(QtCore.QSize(50, 40))
        self.saveBtn.setMaximumSize(QtCore.QSize(50, 40))
        self.saveBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 196, 255, 50);\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 196, 255, 100);\n"
"}")
        self.saveBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/save_21411.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon3)
        self.saveBtn.setIconSize(QtCore.QSize(30, 30))
        self.saveBtn.setObjectName("saveBtn")
        self.verticalLayout_3.addWidget(self.saveBtn)
        self.gridLayout_4.addWidget(self.frame_2, 2, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.navBar)
        self.frame.setMinimumSize(QtCore.QSize(50, 40))
        self.frame.setMaximumSize(QtCore.QSize(50, 40))
        self.frame.setStyleSheet("background:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.openBtn = QtWidgets.QPushButton(self.frame)
        self.openBtn.setMinimumSize(QtCore.QSize(50, 40))
        self.openBtn.setMaximumSize(QtCore.QSize(50, 40))
        self.openBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 196, 255, 50);\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 196, 255, 100);\n"
"}")
        self.openBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/Folder_Open_2dd6988.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openBtn.setIcon(icon4)
        self.openBtn.setIconSize(QtCore.QSize(30, 30))
        self.openBtn.setObjectName("openBtn")
        self.verticalLayout_4.addWidget(self.openBtn)
        self.gridLayout_4.addWidget(self.frame, 2, 1, 1, 1)
        self.optionBtn = QtWidgets.QPushButton(self.navBar)
        self.optionBtn.setMinimumSize(QtCore.QSize(50, 40))
        self.optionBtn.setMaximumSize(QtCore.QSize(50, 40))
        self.optionBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 196, 255, 50);\n"
"}\n"
"QPushButton:checked{\n"
"background: rgba(0, 196, 255, 100);\n"
"}")
        self.optionBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/Menu_icon_icon-icons.corm_71858.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optionBtn.setIcon(icon5)
        self.optionBtn.setIconSize(QtCore.QSize(40, 40))
        self.optionBtn.setCheckable(True)
        self.optionBtn.setObjectName("optionBtn")
        self.gridLayout_4.addWidget(self.optionBtn, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 4, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 2, 3, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_4)
        self.gridLayout.addWidget(self.navBar, 1, 0, 1, 3)
        self.verticalLayout.addWidget(self.background)
        self.horizontalLayout.addWidget(self.border)

        self.retranslateUi(Form)
        self.exitBtn.clicked.connect(Form.close)
        self.minBtn.clicked.connect(Form.showMinimized)
        self.blurSlide.valueChanged['int'].connect(self.imageLbl.setNum)
        self.brightSlide.valueChanged['int'].connect(self.imageLbl.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hoeheLbl.setText(_translate("Form", "Höhe"))
        self.label_4.setText(_translate("Form", "ColorMap:"))
        self.breiteLbl.setText(_translate("Form", "Breite"))
        self.clrMapCombo.setItemText(0, _translate("Form", "Normal"))
        self.clrMapCombo.setItemText(1, _translate("Form", "Autumn"))
        self.clrMapCombo.setItemText(2, _translate("Form", "Bone"))
        self.clrMapCombo.setItemText(3, _translate("Form", "Jet"))
        self.clrMapCombo.setItemText(4, _translate("Form", "Winter"))
        self.clrMapCombo.setItemText(5, _translate("Form", "Rainbow"))
        self.clrMapCombo.setItemText(6, _translate("Form", "Ocean"))
        self.clrMapCombo.setItemText(7, _translate("Form", "Summer"))
        self.clrMapCombo.setItemText(8, _translate("Form", "Spring"))
        self.clrMapCombo.setItemText(9, _translate("Form", "Cool"))
        self.clrMapCombo.setItemText(10, _translate("Form", "Hsv"))
        self.clrMapCombo.setItemText(11, _translate("Form", "Pink"))
        self.clrMapCombo.setItemText(12, _translate("Form", "Hot"))
        self.brightnessLbl.setText(_translate("Form", "Umkehrung: "))
        self.blurLbl_2.setText(_translate("Form", "Eigenschaften:"))
        self.blurLbl.setText(_translate("Form", "Blur:"))
        self.maaLbl.setText(_translate("Form", "Maaße:"))
        self.pathLbl.setText(_translate("Form", "Path..."))
        self.appName.setText(_translate("Form", "OpenCV Bildbearbeitung"))
import images.img

